[".tmux/plugins/tpm"]
    type = "git-repo"
    url = "https://github.com/tmux-plugins/tpm.git"
    refreshPeriod = "168h"
[".config/zsh/plugins/zsh-autosuggestions"]
    type = "git-repo"
    url = "https://github.com/zsh-users/zsh-autosuggestions.git"
    refreshPeriod = "168h"
[".local/share/nvim/site/pack/packer/opt/packer.nvim"]
    type = "git-repo"
    url = "https://github.com/wbthomason/packer.nvim.git"
    refreshPeriod = "168h"
