# ---------------------------------------------------------------------
# Starship configuration
#
# All symbols come from this preset:
# https://starship.rs/presets/#nerd-font-symbols
#
# To use them install a patched Nerd Front:
# https://www.nerdfonts.com
# ---------------------------------------------------------------------
add_newline = true
scan_timeout = 10

[username]
disabled = false

[hostname]
disabled = true

[kubernetes]
disabled = true

[directory]
disabled = false
fish_style_pwd_dir_length = 1

[git_branch]
symbol = " "
disabled = false

[git_commit]
only_detached = false
disabled = false

[git_state]
disabled = false

[git_status]
disabled = false
staged.style = "green"

[hg_branch]
symbol = " "
disabled = false

[docker_context]
symbol = " "
disabled = true

[package]
symbol = " "
disabled = false

[dotnet]
disabled = true

[elixir]
symbol = " "
disabled = false

[elm]
symbol = " "
disabled = true

[erlang]
disabled = false

[golang]
symbol = " "
disabled = false

[haskell]
symbol = " "
disabled = false

[java]
symbol = " "
disabled = false

[julia]
symbol = " "
disabled = false

[nodejs]
disabled = false

[php]
symbol = " "
disabled = true

[python]
symbol = " "
disabled = false

[ruby]
symbol = " "
disabled = false

[rust]
symbol = " "
disabled = false

[terraform]
disabled = true

[nix_shell]
symbol = " "
disabled = true

[conda]
symbol = " "
disabled = true

[memory_usage]
symbol = " "
disabled = true

[aws]
symbol = " "
disabled = true

[env_var]
disabled = true

[crystal]
disabled = true

[cmd_duration]
disabled = false
min_time = 500
show_milliseconds = true

[custom]
disabled = true

[line_break]
disabled = false

[jobs]
disabled = false

[battery]
full_symbol = ""
charging_symbol = ""
discharging_symbol = ""
disabled = true

[time]
disabled = true

[character]
disabled = false
use_symbol_for_status = true
