# ---------------------------------------------------------------------
# Starship configuration
# ---------------------------------------------------------------------
add_newline = true
scan_timeout = 10

format = """\
    $username\
    $hostname\
    $kubernetes\
    $directory\
    $git_branch\
    $git_commit\
    $git_state\
    $git_status\
    $hg_branch\
    $docker_context\
    $package\
    $dotnet\
    $elixir\
    $elm\
    $erlang\
    $golang\
    $haskell\
    $java\
    $julia\
    $nodejs\
    $ocaml\
    $php\
    $purescript\
    $python\
    $ruby\
    $rust\
    $terraform\
    $zig\
    $nix_shell\
    $conda\
    $memory_usage\
    $aws\
    $env_var\
    $crystal\
    $cmd_duration\
    $line_break\
    $jobs\
    $battery\
    $time\
    $character\
    """

[username]
disabled = false

[hostname]
disabled = true

[kubernetes]
disabled = true

[directory]
disabled = false
fish_style_pwd_dir_length = 1

[git_branch]
symbol = "🌱 "
disabled = false

[git_commit]
only_detached = false
disabled = false

[git_state]
disabled = false

[git_status]
disabled = false # flag-git-status
untracked = "[?](bold yellow)"
staged = "[+](bold green)"
stashed = "[\\$](bold purple)"

[hg_branch]
disabled = false

[docker_context]
disabled = false

[package]
disabled = true

[dotnet]
disabled = true

[elixir]
disabled = false

[elm]
disabled = true

[erlang]
disabled = false

[golang]
disabled = false

[haskell]
disabled = false

[java]
disabled = false

[julia]
disabled = false

[nodejs]
disabled = false

[php]
disabled = true

[python]
disabled = false

[ruby]
disabled = false

[rust]
disabled = false

[terraform]
symbol = " "
disabled = false

[nix_shell]
disabled = true

[conda]
disabled = true

[memory_usage]
symbol = " "
disabled = true

[aws]
disabled = true

[env_var]
disabled = true

[crystal]
disabled = true

[cmd_duration]
disabled = true
min_time = 500
show_milliseconds = true

[custom]
disabled = true

[line_break]
disabled = false

[jobs]
disabled = false

[battery]
disabled = true

[time]
disabled = true

[character]
disabled = false
