#!/usr/bin/env bash

# Script and idea taken from:
# https://github.com/clehner/.files/blob/08c99194fc9896651367d2c161cc13b127fdd879/i3/exit

desktop() {
  dbus-send --system --print-reply --dest="org.freedesktop.$1"\
    /org/freedesktop/$2 org.freedesktop.${2/\//.}.$3
}

case $1 in
  lock)
    xautolock -locknow
    ;;
  suspend)
    killall -SIGUSR1 dunst # pause notifications
    xautolock -locknow
    desktop UPower UPower Suspend
    killall -SIGUSR2 dunst # resume notifications
    ;;
  reboot)
    desktop ConsoleKit ConsoleKit/Manager Restart
    ;;
  poweroff)
    desktop ConsoleKit ConsoleKit/Manager Stop
    ;;
  *)
    echo >&2 "Usage: $0 lock|suspend|reboot|poweroff"
    exit 1
esac
