#!/usr/bin/env zsh

# Emits Git metadata for use in a Zsh prompt.
#
# Based on Geoffrey Grosenbach's modified version of:
#   https://github.com/benhoskings/dot-files/blob/master/files/bin/git_cwd_info
#
# Added more git status info.

GIT_REPO_PATH=`git rev-parse --git-dir 2>/dev/null`
if [[ $GIT_REPO_PATH != '' ]]; then

  GIT_BRANCH=`git symbolic-ref -q HEAD | sed 's/refs\/heads\///'`
  GIT_COMMIT_ID=`git rev-parse --short HEAD 2>/dev/null`

  GIT_MODE=""
  if [[ -e "$GIT_REPO_PATH/BISECT_LOG" ]]; then
    GIT_MODE=" +bisect"
  elif [[ -e "$GIT_REPO_PATH/MERGE_HEAD" ]]; then
    GIT_MODE=" +merge"
  elif [[ -e "$GIT_REPO_PATH/rebase" || -e "$GIT_REPO_PATH/rebase-apply" || -e "$GIT_REPO_PATH/rebase-merge" || -e "$GIT_REPO_PATH/../.dotest" ]]; then
    GIT_MODE=" +rebase"
  fi

  GIT_STATUS=""
  if ! git diff --quiet --cached 2>/dev/null; then
    GIT_STATUS+="%{[32m%}+%{[0m%}"
  fi

  if [[ `git ls-files -u` != "" ]]; then
    GIT_STATUS+="%{[35m%}*%{[0m%}"
  fi

  if [[ `git ls-files -m` != "" ]]; then
    GIT_STATUS+="%{[31m%}!%{[0m%}"
  fi

  if [[ `git ls-files --others --exclude-standard` != "" ]]; then
    GIT_STATUS+="%{[31m%}?%{[0m%}"
  fi

  echo "$GIT_STATUS %{[36m%}$GIT_BRANCH %{[33m%}$GIT_COMMIT_ID%{[31m%}$GIT_MODE%{[0m%}"
fi
