#!/usr/bin/env zsh

function _validate() {
  if which $1 &>/dev/null 2>&1; then
    echo "---> $1: [32mOK[0m"
  else
    echo "---> $1: [31mNOT INSTALLED[0m"
  fi
}

echo "-> Checking needed packages"
_validate 'stow'
_validate 'git'

# vim:set ft=zsh:
