#!/usr/bin/env ruby

require File.join(File.dirname(__FILE__), "common")

with_stow do |package|
  _say "Installing #{package}"
  `stow -t ~ #{package}`
end

with "git" do
  _say "Installing vim dependencies"
  `mkdir -p vim/.vim/bundle`
  `git clone https://github.com/gmarik/Vundle.vim.git vim/.vim/bundle/Vundle.vim`
end

with "vim" do
  _say "Launching Vim to install plugins (this may take a while)"
  pid = fork { exec "vim +PluginInstall +qall" }
  Process.wait pid
end

_say "All done!"

exit

# vim:set ft=ruby:
