#!/usr/bin/env ruby

require 'pathname'

def _error(msg)
  $stderr.puts "---> [31mError: #{msg} was not found in the system[0m"
end

if system("which git &>/dev/null 2>&1")
  $stdout.puts "---> Initializing git submodules"
  `git submodule init`
  `git submodule update`
else
  _error 'git'
  exit false
end

if system("which stow &>/dev/null 2>&1")
  Pathname.glob('*/').map(&:to_s).each do |package|
    unless package =~ /scripts/
      $stdout.puts "---> Installing #{package}"
      `stow -t ~ #{package}`
    end
  end
else
  _error 'stow'
  exit false
end

exit

# vim:set ft=ruby:
