#!/usr/bin/env ruby

require File.join(File.expand_path(File.dirname(__FILE__)), "common")

with! "git" do
  _say "Installing vim dependencies"
  `mkdir -p vim/.vim/autoload`
  `curl -fLo vim/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim`
end

with_stow! do |package|
  _say "Installing #{package}"
  `stow -t ~ #{package}`
end

with! "vim" do
  _say "Launching Vim to install plugins (this may take a while)"
  defer "vim +PlugInstall +qall"
end

with "nvim" do
  _say "Configure Neovim with Vim files"
  `mkdir -p ~/.config`
  `ln -s $PWD/vim/.vim ~/.config/nvim`
  `ln -s $PWD/vim/.vimrc ~/.config/nvim/init.vim`
  defer "nvim +PlugInstall +qall"
end

_say "All done!"

exit

# vim:set ft=ruby:
