#!/usr/bin/env ruby

require File.join(File.expand_path(File.dirname(__FILE__)), "common")

with_stow do |package|
  _say "Removing #{package}"
  `stow -t ~ -D #{package}`
end

_say "Removing vim dependencies"
`rm -fr vim/.vim/plugged/*`

exit

# vim:set ft=ruby:
