# ~/.zprofile: This file is executed after /etc/zprofile, and it is executed
# in login shells. It is executed after ~/.zshenv and usually the main
# /etc/zprofile would reset the PATH, so better to put any PATH modification
# here.

# In ZSH $PATH is tied to $path, so we can use it as a global (-g) array (-a) with unique (-U) elements
typeset -U path

# hombrew uses the /opt/homebrew path in Apple Silicon machines
if [[ -d /opt/homebrew ]]; then
  export HOMEBREW_PREFIX="/opt/homebrew"
  export HOMEBREW_CELLAR="/opt/homebrew/Cellar"
  export HOMEBREW_REPOSITORY="/opt/homebrew"
  export PATH="/opt/homebrew/bin:/opt/homebrew/sbin${PATH+:$PATH}"
  export MANPATH="/opt/homebrew/share/man${MANPATH+:$MANPATH}:"
  export INFOPATH="/opt/homebrew/share/info:${INFOPATH:-}"
fi

# go PATH changes
if [[ -d "$HOME/go" ]] ; then
  export GOPATH="$HOME/go"
  path=("$GOPATH/bin" $path)
fi

# rust PATH changes
if [[ -d "$HOME/.cargo/bin" ]] ; then
  path=("$HOME/.cargo/bin" $path)
fi

# local bins
path=(".safe/../bin" "$HOME/.local/bin" $path)

# vim:set ft=zsh:
