# ~/.zshenv: This file is executed in second place after /etc/zshenv

local config_dir="$HOME/.config/zsh"

if [[ -n $XDG_CONFIG_HOME ]] ; then
  config_dir=$XDG_CONFIG_HOME
fi

# Load files from $HOME/.config/zsh/env.d/
local env_d=$config_dir/env.d
if test -d $env_d; then
  for env in $env_d/*.zsh; do
    test -r $env && source $env
  done
  unset env
fi

if [[ ! -o login ]]; then
  # Since there are custom PATH modifications in the zprofile,
  # let's load it as if we were in a login shell
  source "$HOME/.zprofile"
fi

# vim:set ft=zsh:
